export const TYPE_COLORS = {
  fire:     { bg: 'bg-orange-500',  text: 'text-orange-100' },
  water:    { bg: 'bg-blue-500',    text: 'text-blue-100' },
  grass:    { bg: 'bg-green-500',   text: 'text-green-100' },
  electric: { bg: 'bg-yellow-400',  text: 'text-yellow-900' },
  psychic:  { bg: 'bg-pink-500',    text: 'text-pink-100' },
  ice:      { bg: 'bg-cyan-400',    text: 'text-cyan-900' },
  dragon:   { bg: 'bg-indigo-600',  text: 'text-indigo-100' },
  dark:     { bg: 'bg-gray-700',    text: 'text-gray-100' },
  fairy:    { bg: 'bg-pink-300',    text: 'text-pink-900' },
  fighting: { bg: 'bg-red-700',     text: 'text-red-100' },
  poison:   { bg: 'bg-purple-500',  text: 'text-purple-100' },
  ground:   { bg: 'bg-amber-600',   text: 'text-amber-100' },
  rock:     { bg: 'bg-stone-500',   text: 'text-stone-100' },
  bug:      { bg: 'bg-lime-500',    text: 'text-lime-900' },
  ghost:    { bg: 'bg-violet-700',  text: 'text-violet-100' },
  steel:    { bg: 'bg-slate-400',   text: 'text-slate-900' },
  normal:   { bg: 'bg-gray-400',    text: 'text-gray-900' },
  flying:   { bg: 'bg-sky-400',     text: 'text-sky-900' },
}